title: Nick Nielsen Tech Writer Portfolio
description: This is my technical writing site.
navbar-links:
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
theme: jekyll-theme-cayman
