title: Nick Nielsen's Technical Writing Portfolio
logo: /logo.jpeg
description: Hi, I'm Nick. This is my technical writing portfolio. Check it out!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
