title: Nick Nielsen, Tech Writer Portfolio
navbar-links:
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
description: This is my technical writing site.
theme: jekyll-theme-cayman
